config/routes.rb
Rails.application.routes.draw do
  # resources :publicacions
  resources :publicaciones do 
    resources :comentarios
  end
  resources :usuarios  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/login' , to: "login#new"
  post '/login', to: "login#create"
  delete '/logout', to: "login#destroy"

  get '/usuarios/:id/muro', to: "usuarios#muro", as: :muro_usuario 

  root "login#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :usuario
  belongs_to :publicacion
end

app/models/publicacion.rb
class Publicacion < ApplicationRecord
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :sesion
  def sesion
    redirect_to login_path if session[:id].nil?
  end 
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  def create
    comentario = Comentario.new
    comentario.contenido = params[:comentario][:contenido]
    comentario.usuario_id = session[:id]
    comentario.publicacion_id = params[:publicacion_id]    
    comentario.save

    redirect_to muro_usuario_path(session[:id])
  end 
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :sesion
  def new
  end

  def create
    usuario = params[:usuario]
    password = params[:password]
    usuario = Usuario.where("nombre = ? and paterno = ?", usuario,password).first
    if usuario.nil?
      flash.now[:error] = "Usuario o password incorrectos"
      render :new
    else
      session[:id] = usuario.id
      session[:nombre] = usuario.nombre
      redirect_to muro_usuario_path(usuario)
    end
  end

  def destroy
    session[:id] = nil
    session[:nombre] = nil
    redirect_to login_path
  end
end

app/controllers/publicaciones_controller.rb
class PublicacionesController < ApplicationController
  before_action :set_publicacion, only: [:show, :edit, :update, :destroy]

  # GET /publicaciones
  # GET /publicaciones.json
  def index
    @publicaciones = Publicacion.all
  end

  # GET /publicaciones/1
  # GET /publicaciones/1.json
  def show
  end

  # GET /publicaciones/new
  def new
    @publicacion = Publicacion.new
  end

  # GET /publicaciones/1/edit
  def edit
  end

  # POST /publicaciones
  # POST /publicaciones.json
  def create
    @publicacion = Publicacion.new(publicacion_params)
    @publicacion.usuario_id = session[:id]

    respond_to do |format|
      if @publicacion.save
        format.html { redirect_to @publicacion, notice: 'Publicacion was successfully created.' }
        format.json { render :show, status: :created, location: @publicacion }
      else
        format.html { render :new }
        format.json { render json: @publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publicaciones/1
  # PATCH/PUT /publicaciones/1.json
  def update
    respond_to do |format|
      if @publicacion.update(publicacion_params)
        format.html { redirect_to @publicacion, notice: 'Publicacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @publicacion }
      else
        format.html { render :edit }
        format.json { render json: @publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publicaciones/1
  # DELETE /publicaciones/1.json
  def destroy
    @publicacion.destroy
    respond_to do |format|
      format.html { redirect_to publicaciones_url, notice: 'Publicacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publicacion
      @publicacion = Publicacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publicacion_params
      params.require(:publicacion).permit(:titulo, :contenido, :usuario_id)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def muro
    @publicaciones = Publicacion.where(usuario_id: session[:id])
    @comentario = Comentario.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :paterno, :materno, :rfc, :clav)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/publicaciones_helper.rb
module PublicacionesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedSocial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">    
      <%= link_to "Salir", logout_path, method: :delete%>
      <%= yield %>
    </div> 
  </body>
</html>

app/views/login/new.html.erb
<div class="col-md-6 mx-auto mt-5">
<h3>Bienvenido</h3>

<span class="badge badge-danger"><%= flash[:error]%></span>
<%= form_with(url: login_path, local: true) do %>
  <div class="form-group">
    <%= label_tag :usuario%>
    <%# <label for="exampleInputEmail1">Email address</label> %>
    <%= text_field_tag :usuario, nil, class: 'form-control'%>
    <%# <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">     %>
  </div>
  <div>
    <%= label_tag :password%>
    <%= password_field_tag :password, nil, class: 'form-control'%>
  </div>
  <br>
  <br>
  <%= submit_tag "Entrar", class:'btn btn-primary'%>
<% end %>
</div>

app/views/publicaciones/_form.html.erb
<%= form_with(model: publicacion, local: true) do |form| %>
  <% if publicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publicacion.errors.count, "error") %> prohibited this publicacion from being saved:</h2>

      <ul>
        <% publicacion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :contenido %>
    <%= form.text_area :contenido %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publicaciones/edit.html.erb
<h1>Editing Publicacion</h1>

<%= render 'form', publicacion: @publicacion %>

<%= link_to 'Show', @publicacion %> |
<%= link_to 'Back', publicaciones_path %>

app/views/publicaciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publicaciones</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Titutlo</th>
      <th scope="col">Contenido</th>
      <th scope="col">Usuario</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @publicaciones.each do |publicacion| %>
      <tr>
        <td><%= publicacion.titulo %></td>
        <td><%= publicacion.contenido %></td>
        <td><%= publicacion.usuario.nombre %></td>
        <td class="text-center"><%= link_to 'Ver', publicacion, :class => 'btn btn-primary text-white' %></td>
        <td class="text-center"><%= link_to 'Editar', edit_publicacion_path(publicacion), :class => 'btn btn-success text-white' %></td>
        <td class="text-center"><%= link_to 'Eliminar', publicacion, :class => 'btn btn-danger text-white',method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>   
  </tbody>
</table>

<br>

<%= link_to 'Nueva Publicacion', new_publicacion_path, :class => 'btn btn-primary text-white' %>

app/views/publicaciones/new.html.erb
<h1>New Publicacion</h1>

<%= render 'form', publicacion: @publicacion %>

<%= link_to 'Back', publicaciones_path %>

app/views/publicaciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @publicacion.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @publicacion.contenido %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @publicacion.usuario_id %>
</p>

<%= link_to 'Edit', edit_publicacion_path(@publicacion) %> |
<%= link_to 'Back', publicaciones_path %>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :paterno %>
    <%= form.text_field :paterno %>
  </div>

  <div class="field">
    <%= form.label :materno %>
    <%= form.text_field :materno %>
  </div>

  <div class="field">
    <%= form.label :rfc %>
    <%= form.text_field :rfc %>
  </div>

  <div class="field">
    <%= form.label :clav %>
    <%= form.number_field :clav %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Paterno</th>
      <th scope="col">Materno</th>
      <th scope="col">Rfc</th>
      <th scope="col">Clav</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.paterno %></td>
        <td><%= usuario.materno %></td>
        <td><%= usuario.rfc %></td>
        <td><%= usuario.clav %></td>
        <td class="text-center"><%= link_to 'Ver', usuario, :class => 'btn btn-primary text-white' %></td>
        <td class="text-center"><%= link_to 'Editar', edit_usuario_path(usuario), :class => 'btn btn-success text-white' %></td>
        <td class="text-center"><%= link_to 'Eliminar', usuario, :class => 'btn btn-danger text-white',method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_usuario_path, :class => 'btn btn-primary text-white' %>

app/views/usuarios/muro.html.erb
<h1>Mis publicaciones</h1>

<% @publicaciones.each do |p| %>
<br>
  <h3><%= p.titulo %></h3>
  <p><%= p.contenido%></p>
  Comentario:
  <%= form_with(model: [p,@comentario], local: true, method: :post) do |f| %>
    <%= f.text_field :contenido, class: 'form-control' %>
    <br>
    <%= f.submit "Enviar", class: 'btn btn-primary'%>
  <% end %>
<% end %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Paterno:</strong>
  <%= @usuario.paterno %>
</p>

<p>
  <strong>Materno:</strong>
  <%= @usuario.materno %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @usuario.rfc %>
</p>

<p>
  <strong>Clav:</strong>
  <%= @usuario.clav %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>